### ISSUE TITLE
Cursor doesn't hide in fullscreen

### ISSUE THREAD

**Issue by brapifra** [MekliCZ/Blow.js#2]
It would be interesting include in the full screen mode one timeout for hidding the cursor when a bit of time it is passed without moving it.
I'm interested in this project, I need a simple but good looking html5 video player, and I think I've found it.
Nevertheless, I think the way a normal user have to include a blow video is too complicated (make a span with a concrete class inside another concrete div...) I recommend you to rethink that. Maybe create a video with a function call? And pass as parameters the user config? I don't know...
Keep working!

**Comment by MekliCZ** [comment]
I'm working primarily in Safari which hides the cursor in fullscreen automatically, thanks for that!
I chose configuration in span because with Blow.js, you can have more players on one page. Configuration in JS is limited, because it's harder to generate players (for example in PHP). If normal user will try to set up Blow.js, he can simply copy all HTML elements from quick start guide and change video source. As I said, because of the complications with generated players, I'm not going to change way how developers can configurate Blow.js.
